local _, ns = ...
-- Where to get gear. Every line was confirmed on a web page (name, slot, level, source).
-- Items are scored in game from their real tooltip, so an entry that turns out to be
-- weaker than what you wear (or not usable by you) is simply not shown.
-- { id, name, level, how, where, note }   how: drop / quest / vendor / crafted
ns.Sources = ns.Sources or {}
ns.SourceClasses = { MAGE = "cloth", WARLOCK = "cloth", PRIEST = "cloth" }

ns.Sources.cloth = {
    -- low-level crafted gear (names and ids read from the game's own recipe lists); the real tooltip decides the level
    { 5542, "Pearl-clasped Cloak", 1, "crafted", "Tailoring", "" },
    { 2584, "Woolen Cape", 1, "crafted", "Tailoring", "" },
    { 2580, "Reinforced Linen Cape", 1, "crafted", "Tailoring", "" },
    { 2570, "Linen Cloak", 1, "crafted", "Tailoring", "" },
    { 253955, "Shadow Circlet", 1, "crafted", "Tailoring", "" },
    { 7048, "Azure Silk Hood", 1, "crafted", "Tailoring", "" },
    { 4314, "Double-Stitched Woolen Shoulders", 1, "crafted", "Tailoring", "" },
    { 5766, "Lesser Wizard's Robe", 1, "crafted", "Tailoring", "" },
    { 253967, "Shadow Gown", 1, "crafted", "Tailoring", "" },
    { 6264, "Greater Adept's Robe", 1, "crafted", "Tailoring", "" },
    { 6263, "Blue Overalls", 1, "crafted", "Tailoring", "" },
    { 2582, "Green Woolen Vest", 1, "crafted", "Tailoring", "" },
    { 2578, "Barbaric Linen Vest", 1, "crafted", "Tailoring", "" },
    { 6240, "Blue Linen Vest", 1, "crafted", "Tailoring", "" },
    { 6239, "Red Linen Vest", 1, "crafted", "Tailoring", "" },
    { 6238, "Brown Linen Robe", 1, "crafted", "Tailoring", "" },
    { 6241, "White Linen Robe", 1, "crafted", "Tailoring", "" },
    { 253901, "Filigreed Pristine Gown", 1, "crafted", "Tailoring", "" },
    { 2568, "Brown Linen Vest", 1, "crafted", "Tailoring", "" },
    { 4308, "Green Linen Bracers", 1, "crafted", "Tailoring", "" },
    { 4318, "Gloves of Meditation", 1, "crafted", "Tailoring", "" },
    { 4310, "Heavy Woolen Gloves", 1, "crafted", "Tailoring", "" },
    { 4307, "Heavy Linen Gloves", 1, "crafted", "Tailoring", "" },
    { 7026, "Linen Belt", 1, "crafted", "Tailoring", "" },
    { 253885, "Novice Arcanist's Sash", 1, "crafted", "Tailoring", "" },
    { 253887, "Novice Ardent's Sash", 1, "crafted", "Tailoring", "" },
    { 7046, "Azure Silk Pants", 1, "crafted", "Tailoring", "" },
    { 4316, "Heavy Woolen Pants", 1, "crafted", "Tailoring", "" },
    { 10048, "Colorful Kilt", 1, "crafted", "Tailoring", "" },
    { 10047, "Simple Kilt", 1, "crafted", "Tailoring", "" },
    { 4309, "Handstitched Linen Britches", 1, "crafted", "Tailoring", "" },
    { 4343, "Brown Linen Pants", 1, "crafted", "Tailoring", "" },
    { 10045, "Simple Linen Pants", 1, "crafted", "Tailoring", "" },
    { 4320, "Spidersilk Boots", 1, "crafted", "Tailoring", "" },
    { 2583, "Woolen Boots", 1, "crafted", "Tailoring", "" },
    { 4312, "Soft-soled Linen Boots", 1, "crafted", "Tailoring", "" },
    { 2569, "Linen Boots", 1, "crafted", "Tailoring", "" },
    { 10046, "Simple Linen Boots", 1, "crafted", "Tailoring", "" },
    { 6787, "White Woolen Dress", 1, "crafted", "Tailoring", "" },
    { 6786, "Simple Dress", 1, "crafted", "Tailoring", "" },
    { 247789, "Novice's Practice Wand", 1, "crafted", "Enchanting", "" },
    { 11287, "Lesser Magic Wand", 1, "crafted", "Enchanting", "" },
    { 1974, "Mindthrust Bracers", 16, "drop", "Shadowfang Keep - trash (rare)", "" },
    { 5201, "Emberstone Staff", 18, "drop", "The Deadmines - Captain Greenskin", "" },
    { 1155, "Rod of the Sleepwalker", 24, "drop", "Blackfathom Deeps - Twilight Lord Kelris", "" },
    { 11288, "Greater Magic Wand", 13, "crafted", "Enchanting", "" },
    { 7691, "Embalmed Shroud", 30, "drop", "Scarlet Monastery Graveyard - Fallen Champion", "" },
    { 9492, "Electromagnetic Gigaflux Reactivator", 28, "drop", "Gnomeregan - Mekgineer Thermaplugg", "" },
    { 10574, "Corpseshroud", 35, "drop", "Razorfen Downs - multiple mobs", "" },
    { 9431, "Papal Fez", 38, "drop", "Uldaman - multiple mobs", "" },
    { 7720, "Whitemane's Chapeau", 39, "drop", "Scarlet Monastery Cathedral - High Inquisitor Whitemane", "" },
    { 9429, "Miner's Hat of the Deep", 39, "drop", "Uldaman - multiple mobs", "" },
    { 10769, "Glowing Eye of Mordresh", 36, "drop", "Razorfen Downs - Mordresh Fire Eye", "" },
    { 7684, "Bloodmage Mantle", 30, "drop", "Scarlet Monastery Graveyard - Bloodmage Thalnos", "" },
    { 7712, "Mantle of Doan", 33, "drop", "Scarlet Monastery Library - Arcanist Doan", "" },
    { 7057, "Green Silken Shoulders", 31, "crafted", "Crafting", "" },
    { 10776, "Silky Spider Cape", 35, "drop", "Razorfen Downs - Tuten'kash", "" },
    { 10762, "Robes of the Lich", 37, "drop", "Razorfen Downs - Amnennar the Coldbringer", "" },
    { 7063, "Crimson Silk Robe", 36, "crafted", "Crafting; recipe sold by Vizzklick (Gadgetzan, Tanaris)", "" },
    { 7054, "Robe of Power", 33, "crafted", "Crafting", "" },
    { 19129, "Everglowing Robe", 30, "quest", "Kill 'Em With Sleep Deprivation - Searing Gorge", "may be Alliance only" },
    { 9448, "Spidertank Oilrag", 28, "drop", "Gnomeregan - Electrocutioner 6000", "" },
    { 11469, "Bloodband Bracers", 35, "quest", "The Captain's Chest - Stranglethorn Vale", "may be Alliance only" },
    { 10705, "Firwillow Wristbands", 38, "quest", "Doling Justice - Feralas", "may be Alliance only" },
    { 4979, "Enchanted Stonecloth Bracers", 35, "quest", "Stone Is Better than Cloth - Badlands", "may be Alliance only" },
    { 7064, "Crimson Silk Gloves", 37, "crafted", "Crafting", "" },
    { 4121, "Gemmed Gloves", 31, "quest", "Hostile Takeover - Stranglethorn Vale", "may be Alliance only" },
    { 10771, "Deathmage Sash", 36, "drop", "Razorfen Downs - Mordresh Fire Eye", "" },
    { 6726, "Razzeric's Customized Seatbelt", 29, "quest", "Safety First - Thousand Needles", "may be Alliance only" },
    { 9407, "Stoneweaver Leggings", 35, "drop", "Uldaman - Ironaya", "" },
    { 7062, "Crimson Silk Pantaloons", 34, "crafted", "Crafting", "" },
    { 12255, "Pale Leggings", 41, "vendor", "Tor'phan (Orgrimmar); also Thralosh (Swamp of Sorrows)", "" },
    { 10578, "Thoughtcast Boots", 33, "drop", "Razorfen Downs - multiple mobs / Ambassador Malcin", "" },
    { 10359, "Everlast Boots", 30, "quest", "Power Stones - Uldaman", "may be Alliance only" },
    { 9588, "Nogg's Gold Ring", 28, "quest", "Nogg's Ring Redo - Orgrimmar", "" },
    { 10710, "Dragonclaw Ring", 32, "quest", "Extinguishing the Idol - Razorfen Downs", "may be Alliance only" },
    { 19520, "Advisor's Ring", 38, "vendor", "Kelm Hargunth (Mor'shan Base Camp, The Barrens)", "" },
    { 6440, "Brainlash", 43, "drop", "Zul'Farrak - Sandfury Executioner, Ruuzlu, Zerillis", "" },
    { 7714, "Hypnotic Blade", 34, "drop", "Scarlet Monastery Library - Arcanist Doan", "" },
    { 7721, "Hand of Righteousness", 39, "drop", "Scarlet Monastery Cathedral - High Inquisitor Whitemane", "" },
    { 10770, "Mordresh's Lifeless Skull", 36, "drop", "Razorfen Downs - Mordresh Fire Eye", "" },
    { 7685, "Orb of the Forgotten Seer", 33, "drop", "Scarlet Monastery Graveyard - Bloodmage Thalnos", "" },
    { 11662, "Ban'thok Sash", 47, "drop", "Blackrock Depths - Ok'thor the Breaker", "" },
    { 14153, "Robe of the Void", 57, "crafted", "Tailoring 300", "" },
    { 18407, "Felcloth Gloves", 57, "crafted", "Tailoring 280 in WoW Forever (300 in Classic Era); pattern drops from Gordok Reaver, Dire Maul", "" },
    { 19682, "Bloodvine Vest", 60, "crafted", "Tailoring 300; pattern sold by Rin'wosho the Trader, Stranglethorn Vale (needs Zandalar Tribe Revered)", "" },
    { 19683, "Bloodvine Leggings", 60, "crafted", "Tailoring 300", "" },
    { 19684, "Bloodvine Boots", 60, "crafted", "Tailoring 300", "" },
    { 18842, "Staff of Dominance", 60, "drop", "Molten Core - Golemagg the Incinerator", "" },
    -- necklaces and trinkets
    { 21934, "Ornate Tigerseye Necklace", 15, "crafted", "Crafted", "" },
    { 21933, "Thick Bronze Necklace", 17, "crafted", "Crafted", "" },
    { 20830, "Amulet of the Moon", 25, "crafted", "Crafted recipe sold by Gelanthis (Silvermoon) / Daniel Bartlett (Undercity)", "" },
    { 5002, "Glowing Green Talisman", 25, "drop", "World drop (no fixed source)", "" },
    { 5003, "Crystal Starfire Medallion", 26, "drop", "World drop (no fixed source)", "" },
    { 6695, "Stygian Bone Amulet", 27, "drop", "Blind Hunter, Razorfen Kraul", "" },
    { 5180, "Necklace of Harmony", 29, "drop", "Singer, Northfold Manor, Arathi Highlands", "" },
    { 13084, "Kaleidoscope Chain", 30, "drop", "World drop (no fixed source)", "" },
    { 7731, "Ghostshard Talisman", 30, "drop", "Azshir the Sleepless, Scarlet Monastery Graveyard", "" },
    { 4614, "Pendant of Myzrael", 30, "drop", "World drop (no fixed source)", "" },
    { 20966, "Jade Pendant of Blasting", 31, "crafted", "Crafted (recipe)", "" },
    { 20967, "Citrine Pendant of Golden Healing", 34, "crafted", "Crafted (recipe)", "" },
    { 13088, "Gazlowe's Charm", 36, "drop", "World drop (no fixed source)", "" },
    { 1714, "Necklace of Calisea", 38, "drop", "World drop (no fixed source)", "" },
    { 7722, "Triune Amulet", 39, "drop", "High Inquisitor Whitemane, Scarlet Monastery Cathedral", "" },
    { 5029, "Talisman of the Naga Lord", 42, "drop", "Lord Sakrasis, Nek'mani Wellspring, Stranglethorn Vale", "" },
    { 7549, "Fairy's Embrace", 42, "drop", "Bloated Redgill (fishing item #13881)", "" },
    { 9641, "Lifeblood Amulet", 43, "drop", "Antu'sul, Zul'Farrak", "" },
    { 13085, "Horizon Choker", 46, "drop", "World drop (no fixed source)", "" },
    { 1315, "Lei of Lilies", 46, "drop", "World drop (no fixed source)", "" },
    { 11946, "Fire Opal Necklace", 47, "drop", "Relic Coffer, Blackrock Depths", "" },
    { 17707, "Gemshard Heart", 48, "drop", "Princess Theradras, Maraudon", "" },
    { 10829, "The Dragon's Eye", 50, "drop", "Shade of Eranikus, Temple of Atal'Hakkar", "" },
    { 18289, "Barbed Thorn Necklace", 51, "drop", "Warpwood mobs, Dire Maul East (Warpwood Quarter)", "" },
    { 21790, "Sapphire Pendant of Winter Night", 51, "crafted", "Crafted", "" },
    { 16623, "Opaline Medallion", 52, "drop", "Wildkin of Elune, Winterspring", "" },
    { 18317, "Tempest Talisman", 53, "drop", "Hydrospawn, Dire Maul East", "" },
    { 21791, "Living Emerald Pendant", 53, "crafted", "Crafted", "" },
    { 22657, "Amulet of the Dawn", 55, "quest", "Epic Armaments of Battle quests, Eastern Plaguelands (Argent Dawn rep)", "" },
    { 1443, "Jeweled Amulet of Cainwyn", 55, "drop", "World drop (no fixed source)", "" },
    { 18691, "Dark Advisor's Pendant", 56, "drop", "Vectus, Scholomance", "" },
    { 22403, "Diana's Pearl Necklace", 56, "drop", "Cannon Master Willey, Stratholme", "" },
    { 18723, "Animated Chain Necklace", 57, "drop", "Ramstein the Gorger, Stratholme", "" },
    { 13141, "Tooth of Gnarr", 58, "drop", "General Drakkisath, Blackrock Spire", "" },
    { 22149, "Beads of Ogre Mojo", 58, "quest", "Falrin's Vendetta, Dire Maul", "" },
    { 22327, "Amulet of the Redeemed", 58, "quest", "Sothos and Jarien's Heirlooms, Stratholme", "" },
    { 14558, "Lady Maye's Pendant", 59, "drop", "~20 mob drops incl. The Husk (WPL), BRS, MC, ZG", "" },
    { 18814, "Choker of the Fire Lord", 60, "drop", "Ragnaros, Molten Core", "" },
    { 21566, "Rune of Perfection", 20, "vendor", "Illiyana Moonblaze (Silverwing Grove, Ashenvale) / Kelm Hargunth (Mor'shan Base Camp, The Barrens)", "" },
    { 4396, "Mechanical Dragonling", 30, "crafted", "Engineering (200); recipe vendors Gnaz Blunderflame / Kaye Toogie", "" },
    { 9149, "Philosopher's Stone", 35, "crafted", "Alchemy (200); recipe from Alchemist Pestlezugg (Tanaris)", "" },
    { 21748, "Figurine - Jade Owl", 35, "crafted", "Jewelcrafting (200)", "" },
    { 21565, "Rune of Perfection", 40, "vendor", "Illiyana Moonblaze (Silverwing Grove, Ashenvale) / Kelm Hargunth (Mor'shan Base Camp, The Barrens)", "" },
    { 10576, "Mithril Mechanical Dragonling", 40, "crafted", "Engineering (250); recipe vendors Ruppo Zipcoil / Kaye Toogie", "" },
    { 10659, "Shard of Afrasa", 45, "quest", "Heroes of Old (Blasted Lands)", "" },
    { 21777, "Figurine - Emerald Owl", 50, "crafted", "Jewelcrafting (285)", "" },
    { 16022, "Arcanite Dragonling", 50, "crafted", "Engineering (300); recipe vendor Kaye Toogie", "" },
    { 11811, "Smoking Heart of the Mountain", 50, "crafted", "Enchanting-crafted (recipe from Blue Dragonspawn / Lord Roccor); vanilla-wow-archive.fandom.com/wiki/Trinket lists it as enchanter-crafted", "" },
    { 11819, "Second Wind", 54, "drop", "Golem Lord Argelmach (Blackrock Depths)", "" },
    { 12930, "Briarwood Reed", 55, "drop", "Jed Runewatcher (Blackrock Spire, rare)", "" },
    { 18371, "Mindtap Talisman", 56, "drop", "Magister Kalendris (Dire Maul West)", "" },
    { 19950, "Zandalarian Hero Charm", 58, "quest", "The Heart of Hakkar (Zul'Gurub; 20-man raid, needs ZG coin/bijou turn-ins)", "20-man raid" },
    { 17064, "Shard of the Scale", 60, "drop", "Onyxia (Onyxia's Lair)", "" },
    { 18820, "Talisman of Ephemeral Power", 60, "drop", "Molten Core bosses (Magmadar, Golemagg, Baron Geddon, Garr)", "" },
    { 19288, "Darkmoon Card: Blue Dragon", 60, "quest", "Darkmoon Beast Deck (Darkmoon Faire)", "" },
    { 19290, "Darkmoon Card: Twisting Nether", 60, "quest", "Darkmoon Portals Deck (Darkmoon Faire)", "" },
}
